### ISSUE TITLE
[epic] MarkdownDB site (landing page) and "launch"

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#1]
Landing page / launch announce

Objective: can announce the "idea" and prototype on e.g. hacker news

I'm imagining we 3 pieces of core content (which could be posts/pages in themselves) which then inform the main front page

- Why: what's cool about markdowndb
- What: the vision of markdowndb, how it works at a high level and where it's going
- How: some concrete detail (a demo, or short video etc)

🚩 I'm not convinced doing this so thoroughly is necessary. Maybe we can just have a rough landing page and flesh out detailed post later 😉 /cc @olayway 

## Acceptance

- [x] Core content
  - [x] Why
  - [x] What
  - [x] How
- [x] Landing page
  - [x] Vision statement
  - [x] Roadmap (maybe in form of features "coming soon")
  - [x] CTA (e.g. sign up / follow us / get in touch / contribute on github)

### Announce

- [x] Hackernews - Rufus Pollock
- [x] Reddit (what channels)
  - [x] r/Markdown
  - [x] r/CMS
  - [x] r/nextjs
  - [ ] ...
- [x] Tweet @olayway (w/ @popovayoana) **[tweet thread ready](https://hackmd.io/435xZ3K1R0aUDUwYiBkm3A), will post tomorrow morning**
- [x] Post on PortalJS https://portaljs.org/blog/markdowndb-launch
- [x] dev-to - i'd repost intro (hero) + quickstart with link to full tutorial at the end (this could be v similar to portaljs post but a bit more oriented to actual use - so actual code snippets etc). https://dev.to/datopian/markdowndb-a-rich-sql-api-to-your-markdown-files-in-seconds-8k8
- [ ] Post on DataHub??

## Tasks

- [x] Brainstorm the main content
  - [x] Collect content - perhaps merge from #7 and also see https://github.com/datopian/portaljs/discussions/899
- [x] Turn into mini posts (?)
- [x] Draft landing page

### 2023-10-11

Minor additions

- [x] Reduce whitespace at top of hero (there's a lot and "Built with ..." is right at bottom of screen)
- [x] Quickstart link in hero and navbar should link to quickstart not tutorial 
- [x] `Built with ❤️ by Datopian` in footer and at bottom of Hero
- [x] Centering the quickstart titles
- [x] Fix-up Github README
- [ ] Review Roadmap

### 2023-10-04

- [x] Update hero section as per discussion in excalidraw
- [x] Create how it works sequence from above story
  - [x] Bonus: turn gif into video and put on youtube and then embed in the hero on the right (can have this and the "how it works" section)
- [x] Leave out "How MarkdownDB fits your world" (for now - we'll add back later)
- [x] Features section ... hmmm (leave for now and we can revisit - what i note here are just thoughts)
  - [x] Can we simplify to have fewer features and 

### 2023-10-07

- [x] Fix theme color bug
- [x] Hero section
  - [x] have new tagline and summary i.e. "A rich SQL API to your markdown files in seconds." and "An open library to transform markdown content into sql-queryable data. Build rich markdown-powered sites easily and reliably."
  - [x] Add 3 key features
  - [x] Image placeholder for video
- [x] Move features up below hero
- [x] Then unified vision
- [x] Then quickstart

#### Quickstart text

1. You have a folder of markdown content e.g.  some blog posts

   1. Each file has some frontmatter

3. Install markdowndb (optional)

2. Index the files using markdowndb `mddb`

3. Query our files: get a list of all our blog posts with their titles

  - sql query
  - js examples (nextjs)

4. A bit more interesting: query just featured blog posts

5. Use in your application with framework your of choice [show js code using this in e.g. getStaticProps]

6. [optional] Running app with blog posts or list of projects  (reuse our screenshot ...)

### Inspirations perhaps for landing pages

These aren't all as relevant (some we just like layout or approach vs actual info architectuve)

- editable.website (like the way it explains the need)
- dub.sh (a nice simple product landing page with clear explanation of what it is)

### Hero section

Title 1: The missing API/interface from your markdown files to a blog/digital garden/notion alterantive/...

Title A:
Welcome to MarkdownDB - your next-level content base. 🔥🔥

Title B:
Unlock the potential of Markdown as data.

Title C:
Reimagining Markdown's potential with MarkdownDB.
...

---

Subtitle A:
Combine the simplicity of Markdown with the capabilities of a database. 🔥

Subtitle B:
From Markdown files to a rich, queryable database in a snap. 🔥🔥 👈👈

Subtitle C:
Elevate your markdown files. Create, extend, and extract with MarkdownDB.

[DEMO gif or side-by-side screenshots of md files opened in e.g. Obsidian and indexed in the db]

### Features / Why MarkdowbDB

- **Power of plain text**: Combination of unstructured content and structured data in simple Markdown files. With MarkdownDB, you no longer have to compromise between the ease of writing in Markdown and the functionality of a full-fledged database.

- **Simplicity at core**: Turn your Markdown files into a queryable, lightweight SQL database.

- **Flexible and extendabile**: Bring your own document types, extend your frontmatter with computed fields and check for errors with with custom validations.

- **Simple API**: Get a list of all or some Markdown files, filter them by frontmatter fields, and more.

- **Do one thing well 😉** markdowndb just gives you a database, an API a super-powerful and extensible way to create those from markdown. We don't provide a UI, live editing of values etc ... (though others may do!) 

- **Open source**: Your content isn’t locked away in proprietary platforms. It’s open, it's free, it’s yours.

- **Not tied to any stack**: Use anywhere you want - NextJS, SvelteKit, from the command line etc etc.

- Images and other assets as well as text

MarkdownDB the Pattern - why use markdown to create a database/collections

- **Power of plain text**: Combination of unstructured content and structured data in simple Markdown files. With MarkdownDB, you no longer have to compromise between the ease of writing in Markdown and the functionality of a full-fledged database.

- Open source/formats

- Combined Structured and unstructured information

- Images and other assets as well as text

#### Phase 1 - Basic Implementation:

- Indexing
  - Conversion of Markdown files into database records
- Structured Data Extraction
  - Extraction of frontmatter data
  - Automatic type casting for simplified queries
- Links Extraction:
  - Extraction of forward links and backlinks
- Basic API:
  - Get a list of all or some of the Markdown files
  - Get a list of forward and/or backlinks to a Markdown file
  - Filter by metadata fields

#### Phase 2 - Advanced Features:

- BYOT (Bring Your Own Types) System:
  - Ability for users to define their own types for more customized data validation and retrieval.
- Plugins system:
  - ...

#### Phase 3 - Optimization:

- Database Optimization:
  - Refinement of database operations for enhanced speed and data integrity.

### The vision

**Unified Content Management**

Imagine a world where Markdown isn’t just text - it’s an entry in a database, it's a source of structured and unstructured data. With MarkdownDB, we aim to balance the simplicity and accessibility of writing in Markdown with the **ability to treat your collection of markdown files like a database** (think Notion) - allowing, for example presenting each markdown file in a folder as a row in a sheet (e.g. for a project list or any other kind of collection), think querying your markdown files like a database e.g. show me documents with a created in the last week with "hello world" in the title or show me all tasks in all documents with "⏭️" emoji in the task (indicating it's next up!)

### How does it work?

1. Extract: From frontmatter, links, tasks, and more - data extraction is comprehensive and intuitive.

2. Index: Effortlessly index a folder of markdown files and transform them into structured databse records.

3. Query: Utilize the simple API to query your content. Whether you’re creating an individual page, generating a tag list, or referencing backlinks, MarkdownDB has got you covered.

[See It in Action]: Dive into our demo video that walks you through how MarkdownDB transforms the familiar markdown syntax into a rich, interactive database. You'll witness how effortlessly you can extend, embed, and extract content, all with the foundational simplicity of Markdown.

# CRF

Old taglines use on github:

MarkdownDB is a pattern and toolkit for using markdown to store collections of stuff. Think a simple open source Airtable or spreadsheet alternative.

**Comment by rufuspollock** [comment]
@olayway great start. I think we can start with something like this and just iterate - let not the best be the enemy of the good 😄

**Comment by rufuspollock** [comment]
Notes from discussion just now:

https://link.excalidraw.com/l/9u8crB2ZmUo/RVethZITOO


- Pattern: idea of using markdown (strictly: collection of markdown files) as an alternative to ...
  - A collection of docs in google drive, in word etc
    - especially of collection of docs that are a collection in the sense of being about the same thing e.g. you are researching smartphones, or making list of your projects
  - google sheets, airtable, notion database etc
  - an alternative overall to notion
- Job stories for markdowndb
  - I want a blog for my static website built in markdown
  - I want a project list where each project is a markdown file
  - I want to catalog my photos
  - I want to make list of X

**Comment by rufuspollock** [comment]
Reviewed in standup. Key points:

- [ ] Reverse taglines and simplify it a bit e.g. Simple, powerful and open-source library to turn markdown files into a SQLite database with JS API.
  - [ ] "Treat markdown as a rich data/content source ... 
- [ ] Don't capitalize markdown

**Comment by olayway** [comment]
@rufuspollock I've updated the README with some content from the landing page and added some basic API reference as well.

**Comment by rufuspollock** [comment]
FIXED. Site is up https://markdowndb.com and we've done some posting.
