### ISSUE TITLE
Publish to npm under `mddb`

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#28]
@olayway let's go with `mddb` for now.

_Originally posted by @rufuspollock in https://github.com/datopian/markdowndb/issues/9#issuecomment-1586048087_
            
```[tasklist]
### Tasks
- [x] publish to npm under `mddb`
- [x] deprecate `@flowershow/markdowndb`
- [x] replace `@flowershow/markdowndb` with `mddb` in our other projects
- [x] update README, docs and examples
```
