### ISSUE TITLE
NextJS blog example using markdowndb

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#68]
Create a tutorial and example in examples folder of using markdowndb to make a simple nextjs based blog.

Reference: https://nextjs.org/learn-pages-router/basics/data-fetching/blog-data - note we are replacing their hand-coded get the blog posts with our quicker version and explaining the extra stuff we can do.

## Acceptance

- [x] Tutorial written **🚧2023-11-22  see sketch below** ✅2023-11-30 https://github.com/datopian/markdowndb/pull/76
- [x] Example in `examples` folder showing finished state (in perfect world we have a branch with each major change in tutorial being a commit so we can point to that)  ✅2023-11-30 https://github.com/datopian/markdowndb/pull/76
 
## Tasks

- [x] Draft an outline of tutorial  ✅2023-11-30 https://github.com/datopian/markdowndb/pull/76
- [x] Roughly fill it in and write the code as you go ...
  - [x] Review together in a pull request (you can submit even at first step as a draft PR and we keep reviewing)
- [x] Fill it out ...
- [x] Done ...

## Notes

Something like this:

- we're going to create a nextjs based blog with help of markdowndb
- here's a simple nextjs project
- here's a folder with 3 blog posts
- here's some code to create the blog listing page
- we need to load those blog posts and get their titles etc
- let's use markdowndb
  - install
  - use: here's the code snippet
- ok, so we could have done that by hand ...
- but here are some cool features
  - look ma, no front matter: auto-extract title for us from the first heading in the file. auto-extract an image
  - validation! suppose we add a blog post and forget to add an image field. now our site will erro
    - we could check for this easily in markdowndb ... here's how
  - tags: just set tags with hashbang

**Comment by mohamedsalem401** [comment]
I drafted the tutorial and encountered an issue while attempting to write a basic code for creating a nextjs blog with MarkdownDB:
![image](https://github.com/datopian/markdowndb/assets/67981832/ada5ae89-d969-4a50-ad45-fe89c2f187e0)
 
It seems that this issue might be related to #44. I'll delve into debugging to identify and address the problem.

**Comment by mohamedsalem401** [comment]
This is done  ✅2023-11-30 https://github.com/datopian/markdowndb/pull/76
