### ISSUE TITLE
Migrate markdowndb to its own repo

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#8]
We want markdowndb split out from Flowershow so that it is more visible and can be more cleanly reused and contributed to

## Acceptance

NB: removing from Flowershow is *not* part of this work (will be a follow up in flowershow and once we have a release setup)

- [x] Has own repo at datopian/markdowndb **✅2023-04-28**
  - [x] Includes description
- [x] README and code migrated from https://github.com/datopian/flowershow/tree/main/packages/markdowndb
- [x] Code working locally e.g. tests, etc. installation works
- [x] Migrate existing issues and discussions from flowershow, datahub-next etc  **🚧2023-05-02 have migrated all discussions so far**
   - [x] Flowershow discussions
   - [x] Flowershow issues **no open issues to migrate**
   - [x] DataHub-next issues **no open issues to migrate**

## Tasks

- [x] Create the repo
- [x] Migrate current README and code there from https://github.com/datopian/flowershow/tree/main/packages/markdowndb
- [x] Make any necessary corrections
- [x] Migrate existings discussions and material there

**Comment by rufuspollock** [comment]
@olayway i did a crude copy and paste plus change package name to `markdowndb`. I imagine some fixing may be needed for it to work given it was part of a monorepo ...

**Comment by olayway** [comment]
@rufuspollock I've just created a PR with the coding part of this issue. As for the issues to migrate, there are none on the Flowershow repo. And I think none on the next-datahub (assuming that we don't want to move closed issues).

**Comment by rufuspollock** [comment]
@olayway just migrated last issues from flowershow so i think everything done here and we can close.
